---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install Git
    yum: name=git state=present
  - name: Install Maven
    yum: name=maven state=present
  - name: Install Chromium
    yum: name=chromium state=present
  - name: Install docker
    yum: name=docker state=present
  - name: Start docker
    service: name=docker state=started
  - name: Get the dockerfile from github
    git: repo="https://github.com/meerasankarath/dockerfile.git" dest=/tmp
  - name: Build the dockerfile
    command: chdir=/tmp docker build -t deploy:ansible1 -f dockerfile
  - name: Run the docker image
    command: docker run -itd -P deploy:ansible1
  
